### ISSUE TITLE
May Todo List

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1445]
- [x] Fix Losing Bonus Ability #Issue: https://github.com/darklordabc/Legends-of-Dota-Redux/issues/1444

- [x] Fix Save/Load Issue for ban lists

- [x] Fix Wisp breaking hero builder

- [ ] Fix remaining issues with dota imba abilities

- [x] Fix bots reciving "Generic Ability" blank abilities https://github.com/darklordabc/Legends-of-Dota-Redux/issues/1391

- [x] Add the new mutations from the official dota mutation mode into redux

- [x] Add a turbo courier mutator

- [ ] Fix Give Item Cheat not working from menu

- [ ] Tome of Exp ability does not give ability point when used to level up (Maybe tome of knowledge has some problem?)

- [x] Make sure consumable items are up to date with latest dota

- [ ] Fix and readd Divided We Stand

- [ ] Fix Disruption having "No Charges". Bugs triggers with Magnus at least, and probably other heros.

- [ ] Update bounty rune to match current version of where team gets the gold
- [ ] Create advanced controls for bots

**Comment by ForbiddenFruitPOD** [comment]
I think adding the updated items (in some cases), rather than replacing them makes sense where the item is extremely different. An example is Monkey King Bar. Previously, it had attack speed bonus rather than damage bonus. I think it would be nice to be able to buy the old version or new version.

For divided we stand, would it be a troll combo with tempest double? Would divided we stand be a single player ability?

**Comment by darklordabc** [comment]
It would be a single player ability. 

I'll check the changes that have happened to the items.

**Comment by Wouterz90** [comment]
- [x] periodic_spellcast
- [x] Tested
- [x] Add in redux
- [x] vampire
- [x] Tested
- [ ] resurrect_teammates
- [ ] Tested
- [x] killstreak_power
- [x] Tested
- [x] fast_runes
- [x] Tested
- [ ] super_runes
- [ ] Tested
- [x] cooldown_reduction
- [x] Tested
- [x] death_explosion
- [x] Tested
- [x] death_gold_dropped
- [x] Tested
- [x] random_lane_creeps
- [ ] Tested
- [x] no_health_bars
- [x] Tested

**Comment by Wouterz90** [comment]
...ripts\abilities\hero_perks\npc_dota_hero_medusa_perk.lua:82: attempt to perform arithmetic on field 'manaRegenPerToggle' (a nil value)
stack traceback:
	...ripts\abilities\hero_perks\npc_dota_hero_medusa_perk.lua:82: in function <...ripts\abilities\hero_perks\npc_dota_hero_medusa_perk.lua:80>
