### ISSUE TITLE
Improve Tracking with getdotastats.com

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#146]
Current the mod is [being tracked by getdotastats.com](https://getdotastats.com/#s2__mod?id=142), and it does offer some nice data, but there is plenty of room for improvements. 
- [ ]  Rename to "Legends of Dota: Redux" instead of "Legends of Dota (darklordABC)"
- [ ] Improve "Player Values" page: Currently the mod does not keep any stats on player values. Compare this to [Original LoD](https://getdotastats.com/#s2__mod_cpv?id=3). [Our page](https://getdotastats.com/#s2__mod_cpv?id=142) should be improved so that we keep at least all the stats that original lod does, these are: Hero picked, attribute picked, team, level reached, kills, assists, deaths, gold per min, xp per min, gold, items 1 to 6, abilities 1 to 6.
- [x] ~~Create list of most popular abilities: A list of all abilities, ranked by popularity of usage. This can be based on ability data from above.~~ (To be done in another issue)
- [x] Add tracking of new vote options: In all_pick_6, the site currently only tracks the bans vote, 
  ![image](https://cloud.githubusercontent.com/assets/16277198/17191762/dbb3a352-548e-11e6-88a1-c229edfd47aa.png)
  it should be improved so it also tracks the "Voting fast start" and the "Voting disabled balance".

**Thats it for now, I'll add more as I think of them...**
