### ISSUE TITLE
GUI Issues Master List

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#498]
**Update:** Not up to date
- [x]  You can only see one line of chat during gamesetup #496 
- [x] Improve order of hints #437 **(HALF DONE)**
- [x] Heros are missing in GUI in single draft #484 
- [x] Credits are broken #515 
- [ ] Reconnecting during baning phase breaks it #528

**Comment by darklordabc** [comment]
Too old
